---
- name: Creates an crontab entry to put the wlan0 interface in promiscuous mode. Needed for metallb to functiomn properly"
  ansible.builtin.cron:
    name: "set wlan0 to promiscuous mode"
    special_time: reboot
    job: "sleep 30 && sudo ifconfig wlan0 promisc"

- name: Creates an crontab entry to put the eth0 interface in promiscuous mode. Needed for metallb to functiomn properly"
  ansible.builtin.cron:
    name: "set eth0 to promiscuous mode"
    special_time: reboot
    job: "sleep 30 && sudo ifconfig eth0 promisc"

- name: Ensure the desired udev rules are in place
  ansible.builtin.template:
    src: udev.rules.j2
    dest: /etc/udev/rules.d/99-ansible-managed.rules
    mode: 0644
  notify: Reload udev

- name: Ensure wifi script exists
  ansible.builtin.template:
    src: wifi-check.sh.j2
    dest: /usr/local/bin/wifi-check.sh
    mode: 0555

- name: Schedule wifi check script every 5 minutes
  ansible.builtin.cron:
    name: "check wifi"
    minute: "*/5"
    hour: "*"
    job: "flock -x -n -E 0 /tmp/wifi-check.lock env WLAN_IF=wlan0 /usr/local/bin/wifi-check.sh"
    user: "root"

- name: Setup cron to vacuum journal logs
  ansible.builtin.cron:
    name: "vacuum journal logs"
    special_time: daily
    job: "sudo journalctl --vacuum-time 14d"

- name: Ensure custom resolv.conf is in place
  ansible.builtin.template:
    src: custom-resolv.conf.j2
    dest: /etc/custom-resolv.conf
    mode: 0644