---
- name: Creates an crontab entry to put the wlan0 interface in promiscuous mode. Needed for metallb to functiomn properly"
  ansible.builtin.cron:
    name: "set wlan0 to promiscuous mode"
    special_time: reboot
    job: "sleep 30 && sudo ifconfig wlan0 promisc"

- name: Ensure the desired udev rules are in place
  ansible.builtin.template:
    src: udev.rules.j2
    dest: /etc/udev/rules.d/99-ansible-managed.rules
    mode: 0644
  notify: Reload udev