---
- name: Shut down cluster servers staggered
  hosts: server
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:

- name: Shut down cluster agents staggered
  hosts: agent
  become: true
  gather_facts: true
  serial: 1
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
